### ISSUE TITLE
saptune 3.1 creates /varlog/saptune instead of /var/log/saptune

### ISSUE THREAD

**Issue by thomas-merz** [SUSE/saptune#116]
Please do not create this /varlog directory anymore in future versions because it's annoying when using bash-tab-completion and looking often for logfiles in /var/log.  
Please consider also a cleanup function for this obsolete /varlog directory when updating to future versions via `rmdir` or so…

**Comment by scmschmidt** [comment]
Opened internal bug https://bugzilla.suse.com/show_bug.cgi?id=1215969 to handle this request.
