### ISSUE TITLE
Note 2382421 was updated regarding version number in the comments, but not in the config.  (45 vs 44)

### ISSUE THREAD

**Issue by CBasis** [SUSE/saptune#119]
There is a mismatch between the current version 45 (mentioned in the comment) and the version number in the section, which shows version 44.

https://github.com/SUSE/saptune/blob/920a0ca2f7bf37989514eaa3b1312ee8bd17904a/ospackage/usr/share/saptune/notes/2382421#L5

# 2382421 - Optimizing the Network Configuration on HANA- and OS-Level
# Version **45** from 02.08.2023 in English
 
[version]
VERSION=**44**
DATE=15.06.2023
DESCRIPTION=Optimizing the Network Configuration on HANA- and OS-Level

**Comment by CBasis** [comment]
Sorry for the bad formatting .. Markup kicked in:
------------------------

 Comment: 2382421 - Optimizing the Network Configuration on HANA- and OS-Level
 Comment: Version ***45*** from 02.08.2023 in English
 
 [version]
 VERSION=***44***
 DATE=15.06.2023
 DESCRIPTION=Optimizing the Network Configuration on HANA- and OS-Level

-------------------

**Comment by angelabriel** [comment]
Thanks for reporting. I totally missed that. 
Fix will be available  with the next maintenance update - version 3.1.2, planned mid of March 2024

**Comment by angelabriel** [comment]
saptune 3.1.2 containing the fix was released on 07.03.2024
