### ISSUE TITLE
SAP Note 1410736 - TCP/IP: setting keepalive interval updated recommendation

### ISSUE THREAD

**Issue by esille** [SUSE/saptune#34]
Hi,

SAP Note SAP Note 1410736  (https://launchpad.support.sap.com/#/notes/1410736) was updated on 13.1.2020 with following changes for Linux:

Change the keepalive using sysctl utility.
Use following values

net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_probes = 9

Please have this changes included in latest version of saptune.

Thanks!

Erik

**Comment by angelabriel** [comment]
Thanks for the heads-up and your PR. This help is really appreciated. I have approved and merged your change and will try to get it into the next release of saptune.
